#!/usr/bin/env python

import rospy
import pickle
import sys

from nav_msgs.msg import Path

def save_path(msg):
    pathpoints = [
        (pose.pose.position.x, pose.pose.position.y)
        for pose in msg.poses
    ]

    map_data = {'pathpoints': pathpoints}

    with open(filename, 'wb') as f:
        pickle.dump(map_data,  f)

    rospy.signal_shutdown('Path saved')

if __name__ == '__main__':
    rospy.init_node('path_saver')

    global filename
    filename = filename = sys.argv[1]

    rospy.Subscriber('path', Path, save_path)

    rospy.spin()
